### ISSUE TITLE
dlopen(h264decode.so, 2): Symbol not found: _av_buffer_allocz

### ISSUE THREAD

**Issue by mikezone** [tzwenn/PyOpenAirMirror#12]
when I run main.py
dlopen(h264decode.so, 2): Symbol not found: _av_buffer_allocz, 
what should I do?
hope your reply

$ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 10, in <module>
    import mirror.service
  File "/Users/Mike/Downloads/zzRecord/PyOpenAirMirror/mirror/service.py", line 4, in <module>
    import h264decode
ImportError: dlopen(/Users/Mike/Downloads/zzRecord/PyOpenAirMirror/h264decode.so, 2): Symbol not found: _av_buffer_allocz
  Referenced from: /Users/Mike/Downloads/zzRecord/PyOpenAirMirror/h264decode.so
  Expected in: flat namespace
 in /Users/Mike/Downloads/zzRecord/PyOpenAirMirror/h264decode.so

**Comment by tzwenn** [comment]
This looks to me like another ffmpeg bug.
How did you install it? Is libavutil present?

**Comment by mikezone** [comment]
I Install it recording instruments in INSTALL ( a txt file). It likes
1. run ./configure
2.make
3.make install

**Comment by tzwenn** [comment]
Since you are on macOS anyway, try installing ffmpeg via [homebrew](http://brew.sh).
Make sure your all libraries (including `libavutil` which contains missing `av_buffer_allocz` above) are found.

Unfortunately I cannot otherwise reproduce your problem.
